### ISSUE TITLE
Problem: Application using a different version of React than react-stockcharts will error out

### ISSUE THREAD

**Issue by trevorbernard** [rrag/react-stockcharts#12]
```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
```

Rather than installing react as a dependency, add it as a peer dependency.

E.g.
```
  "peerDependencies": {
    "react": ">=0.13.3 || ^0.14.0-beta3"
  },
```

**Comment by rrag** [comment]
Can you explain how you installed `react-stockcharts` ? this problem will be taken care automatically by npm. did you try `npm dedupe`

I faced this problem once when I was using `npm link` but I got around that once I understood how link works. the solution was to have a soft link to a common `react`

Also react is a `dependency`, I can't remove it from there. I need it for the development of this project.

`peerDependency` has many confusing implications and leads to dependency hellp. It is getting a much needed update in 
https://github.com/npm/npm/releases/tag/v3.0.0

read the following sections

##### peerDependencies
##### Flat, flat, flat!

Thinking about it further, I guess the problem is I have indicated `0.14.0-beta3` as the version and not `>=0.13.3 || ^0.14.0-beta3` in the `dependencies` since beta does not have the `latest` tag on npm. npm install is unable to enforce the versions I believe.

**Comment by trevorbernard** [comment]
> Can you explain how you installed react-stockcharts?

react-stockcharts is a dependency in my package.json and I use `npm install`

Re: peerDependencies

I don't particularly care how the problem is solved only that it's solved. If peer dependencies isn't the simplest solution to the problem, fair enough.

**Comment by rrag** [comment]
I am still not sure what the right solution is. I am exploring the peerDependencies route. Will publish a new version once I figure this out

**Comment by rrag** [comment]
I am using react in both `peerDependencies` and `dependencies`. I saw a few other projects also do that. 

I think the problem was because I was referring to 0.14.0-beta3 and since 0.14.0 is not released yet, npm is not able to enforce the dependencies. I am not sure though.

let me know if the new 0.2.2 on npm addresses the problem. This one uses `react` & `react-dom` as `dependencies` & `peerDependencies`

**Comment by trevorbernard** [comment]
I'm still running into the same problem as my codebase uses react 0.13.x. I unable to migrate to 0.14 as I have to wait for the dependencies in my project to update as well. Is react-stockcharts dependent on features of react 0.14.x? If not then it shouldn't hurt to include 0.13.x in the package.json as well. Otherwise, I'll simply have to wait until my dependencies have caught up.

Best,
Trev

**Comment by rrag** [comment]
The usage of parent based context is a 0.14 feature, I was able to make it work on 0.13 by using a deprecated method `React.withContext`.

I wanted to give higher order components in 0.14 a try, in order to make custom components easy. So those are the 2 features in 0.14 which is are used.

I am sorry you might have to wait this one so 0.14 is released and the dependencies get caught up. Can you use 0.1.3 work till React 0.14 becomes widely used. Is there any feature in react stockcharts 0.2 you are interested in? I can release a patch version by removing the 0,14 dependency and reverting some code changes.

**Comment by trevorbernard** [comment]
CandleStick Chart is the only chart I use in my project. I suspect the other project will catch up soon. In the meantime, I just commented out the CandleStick Chart as an interim solution.

**Comment by rrag** [comment]
I hate to lose an early adopter, I will release a new version and ensure compatibility with `0.13.3`

**Comment by rrag** [comment]
`react-stockcharts@0.2.3` available in npm now with 0.13.3 as dependency. Let me know how this goes.

**Comment by trevorbernard** [comment]
It works beautifully

**Comment by rrag** [comment]
:+1:
