### ISSUE TITLE
mobile pan, zoom (chrome) Uncaught TypeError: chartsToPan.indexOf is not a function

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#122]
<img width="1373" alt="screen shot 2016-08-22 at 14 49 40" src="https://cloud.githubusercontent.com/assets/6270599/17853949/3ea970de-6878-11e6-8005-726bf8e0c839.png">

**Comment by rrag** [comment]
good catch, I have not tested `next` branch in touch devices

**Comment by rrag** [comment]
Fixed

**Comment by poksme** [comment]
This error still shows up when testing on mobile. I created [a pull request](https://github.com/rrag/react-stockcharts/pull/209).
