### ISSUE TITLE
next branch: fitWidth with xScaleProvider, props for EventHandler

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#75]
<img width="1502" alt="screen shot 2016-05-13 at 14 51 03" src="https://cloud.githubusercontent.com/assets/6270599/15247052/30274674-191a-11e6-948e-c224048e1367.png">

**Comment by rrag** [comment]
I pushed to next by mistake, it is not stable code. This is part of the scale rewrite,

**Comment by rrag** [comment]
all examples fixed to use a slightly modified scale, there is no change needed if you use a `d3.time.scale` but if you use the existing `financeEODDiscontinuousScale` or `financeIntradayDiscontinuousScale` there will be a breaking change. I am yet to add more details in the change log.

in short, it is a [2 line change](https://github.com/rrag/react-stockcharts/commit/154bcfe5c5cf71b61889b9ec5b0adc502f363df3#diff-eb889c1cdbc3f0676272228676b275e3),

```diff
-var { financeEODDiscontinuousScale } = ReStock.scale;
+var { discontinuousTimeScaleProvider } = ReStock.scale;
```
and
```diff
<ChartCanvas ...
  xAccessor={d => d.date}
- discontinuous xScale={financeEODDiscontinuousScale()}
+ xScaleProvider={discontinuousTimeScaleProvider}
 ...
```

**Comment by rsklyar** [comment]
i have used financeIntradayDiscontinuousScale 

but, after last commit only one Type Error
<img width="1505" alt="screen shot 2016-05-14 at 02 19 57" src="https://cloud.githubusercontent.com/assets/6270599/15264321/abca9c1c-197a-11e6-8437-da1de0bf850d.png">

**Comment by rrag** [comment]
fixed it, can you try again,

`financeIntradayDiscontinuousScale` or `financeEODDiscontinuousScale` can no longer be used in `next` branch

```diff
<ChartCanvas ...
  xAccessor={d => d.date}
- discontinuous xScale={financeIntradayDiscontinuousScale()}
+ xScaleProvider={discontinuousTimeScaleProvider}
 ...
```

**Comment by rsklyar** [comment]
still have some trubles with fitWidth from next branch (
<img width="1101" alt="screen shot 2016-05-14 at 14 34 05" src="https://cloud.githubusercontent.com/assets/6270599/15268248/221bb6ce-19e1-11e6-9cb7-c21572907b14.png">

couldnt prepare planker, but when window resized, fitWidth doesn't  work

**Comment by rrag** [comment]
I am not able to recreate that issue, are you sure you dont have 2 versions of ReactDOM in your bundle?
