### ISSUE TITLE
problem with MACD.  <rect> attribute y: Expected length, "NaN".

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#91]
```javascript
<Chart id={3} height={150}
	    yExtents={macdCalculator.accessor()}
	    yMousePointerDisplayLocation="right" yMousePointerDisplayFormat={d3.format(".2f")}
	    origin={(w, h) => [0, h - 150]}>
	<XAxis axisAt="bottom" orient="bottom"/>
	<YAxis axisAt="right" orient="right" ticks={2} />
	<MACDSeries calculator={macdCalculator} />
</Chart>
```
when I add 
```javascript
<MACDSeries calculator={macdCalculator} />
```
, it comes errors with 
```javascript
<rect> attribute y: Expected length, "NaN".
<rect> attribute height: Expected length, "NaN".
```
In addition, how to change the colors of MACDTooltip.

**Comment by sunshineying** [comment]
I find that if I make the type of component of ChartCanvas with "hybrid", the errors above are disappeared.  My problem has been solved already.

**Comment by rrag** [comment]
canvas is more forgiving to errors, the problem still exists.

If you share a plunker I can help identify the problem.

**Comment by sunshineying** [comment]
Hi.  I find that it could be with few data. The plunker as follows: 
[http://plnkr.co/edit/uuvkhxcH6ZIGa3P008uJ?p=preview](http://plnkr.co/edit/uuvkhxcH6ZIGa3P008uJ?p=preview)

**Comment by rrag** [comment]
it is a defect. Working on a fix
